apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-dev
resources:
  - ../../base
patches:
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: platform-config
secretGenerator:
  - name: platform-secrets
    envs:
      - secrets.env.example
